# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\Backups\Coding\Projects\s3dl 3.0"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\Backups\Coding\Projects\s3dl 3.0"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\Backups\Coding\Projects\s3dl 3.0\CMakeFiles" "D:\Backups\Coding\Projects\s3dl 3.0\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\Backups\Coding\Projects\s3dl 3.0\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named s3gl

# Build rule for target.
s3gl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 s3gl
.PHONY : s3gl

# fast build rule for target.
s3gl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\s3gl.dir\build.make CMakeFiles/s3gl.dir/build
.PHONY : s3gl/fast

src/Game/Game.obj: src/Game/Game.cpp.obj
.PHONY : src/Game/Game.obj

# target to build an object file
src/Game/Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\s3gl.dir\build.make CMakeFiles/s3gl.dir/src/Game/Game.cpp.obj
.PHONY : src/Game/Game.cpp.obj

src/Game/Game.i: src/Game/Game.cpp.i
.PHONY : src/Game/Game.i

# target to preprocess a source file
src/Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\s3gl.dir\build.make CMakeFiles/s3gl.dir/src/Game/Game.cpp.i
.PHONY : src/Game/Game.cpp.i

src/Game/Game.s: src/Game/Game.cpp.s
.PHONY : src/Game/Game.s

# target to generate assembly for a file
src/Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\s3gl.dir\build.make CMakeFiles/s3gl.dir/src/Game/Game.cpp.s
.PHONY : src/Game/Game.cpp.s

src/Utils/Timer.obj: src/Utils/Timer.cpp.obj
.PHONY : src/Utils/Timer.obj

# target to build an object file
src/Utils/Timer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\s3gl.dir\build.make CMakeFiles/s3gl.dir/src/Utils/Timer.cpp.obj
.PHONY : src/Utils/Timer.cpp.obj

src/Utils/Timer.i: src/Utils/Timer.cpp.i
.PHONY : src/Utils/Timer.i

# target to preprocess a source file
src/Utils/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\s3gl.dir\build.make CMakeFiles/s3gl.dir/src/Utils/Timer.cpp.i
.PHONY : src/Utils/Timer.cpp.i

src/Utils/Timer.s: src/Utils/Timer.cpp.s
.PHONY : src/Utils/Timer.s

# target to generate assembly for a file
src/Utils/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\s3gl.dir\build.make CMakeFiles/s3gl.dir/src/Utils/Timer.cpp.s
.PHONY : src/Utils/Timer.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\s3gl.dir\build.make CMakeFiles/s3gl.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\s3gl.dir\build.make CMakeFiles/s3gl.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\s3gl.dir\build.make CMakeFiles/s3gl.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... s3gl
	@echo ... src/Game/Game.obj
	@echo ... src/Game/Game.i
	@echo ... src/Game/Game.s
	@echo ... src/Utils/Timer.obj
	@echo ... src/Utils/Timer.i
	@echo ... src/Utils/Timer.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

